# Generated by Django 4.2.3 on 2023-07-31 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=100)),
                ('price', models.IntegerField(max_length=12)),
                ('release_date', models.CharField(max_length=15)),
                ('lte_exists', models.CharField(max_length=6)),
                ('slug', models.SlugField()),
            ],
        ),
    ]
